---
# This is an additional inventory to use together with dynamic one (https://github.com/adammck/terraform-inventory)
# example command:
# TF_HOSTNAME_KEY_NAME=name TF_STATE=./ ansible-playbook -i inventory/prod/ -i ~/go/bin/terraform-inventory site.yml
all:
  vars:
    # centos8 defaults
    ansible_user: cloud-user

elasticsearch:
  vars:
    # centos7 settings
    ansible_user: centos

kibana:
  vars:
    # ubuntu settings
    ansible_user: ubuntu
    ansible_python_interpreter: python3

